# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: deploy pakai ssh
        uses: appleboy/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            node publisher.js
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEYS }}
         
